language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn run docs:build
deploy:
  provider: pages
  keep-history: true
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: dysonring/dysonring.github.io
  target-branch: master
  on:
    branch: master
